### ISSUE TITLE
The command "mv resources/assets resources/assets-1519729783" failed. (Windows)

### ISSUE THREAD

**Issue by sorindorobantu** [pvtl/voyager-frontend#1]
On Windows after I run "php artisan voyager-frontend:install" I get an error "The command "mv resources/assets resources/assets-1519729783" failed." 

On Windows the command is "move" not "mv". A quick fix is to change the line 62 in vendor/pvtl/voyager-frontend/src/comands/InstallCommand.php.

Old: `$process = new Process('mv resources/assets resources/assets-' . time());`
New: `$process = new Process('move resources/assets resources/assets-' . time());`

![error](https://user-images.githubusercontent.com/5569161/36726746-8319a464-1bc3-11e8-9485-1d064320543c.PNG)

**Comment by mcnamee** [comment]
Good call @sorindorobantu 
I've updated to use the Laravel FileSystem approach - which should cater cross-platform.

If you install the latest release, then try the install: it should work out better.

Let me know!
