### ISSUE TITLE
Can't install voyager-frontend?

### ISSUE THREAD

**Issue by protected22** [pvtl/voyager-frontend#10]
when i do composer require pvtl/voyager-frontend  I get an error: 

C:\Users\Gebruiker\Desktop\php frmework\Laravel Projects\voyagerfrontend>composer require pvtl/voyager-frontend
Using version ^0.7.0 for pvtl/voyager-frontend
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pvtl/voyager-frontend 0.7.0 requires spatie/laravel-sitemap 3.3.1 -> satisfiable by spatie/laravel-sitemap[3.3.1].
    - Installation request for pvtl/voyager-frontend ^0.7.0 -> satisfiable by pvtl/voyager-frontend[0.7.0].
    - Conclusion: remove laravel/framework v5.6.20
    - Conclusion: don't install laravel/framework v5.6.20
    - spatie/laravel-sitemap 3.3.1 requires illuminate/support ~5.5.0 -> satisfiable by illuminate/support[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28,
 v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - illuminate/support 5.5.x-dev conflicts with laravel/framework[v5.6.20].
    - illuminate/support v5.5.0 conflicts with laravel/framework[v5.6.20].
    - illuminate/support v5.5.16 conflicts with laravel/framework[v5.6.20].
    - illuminate/support v5.5.17 conflicts with laravel/framework[v5.6.20].
    - illuminate/support v5.5.2 conflicts with laravel/framework[v5.6.20].
    - illuminate/support v5.5.28 conflicts with laravel/framework[v5.6.20].
    - illuminate/support v5.5.35 conflicts with laravel/framework[v5.6.20].
    - illuminate/support v5.5.36 conflicts with laravel/framework[v5.6.20].
    - illuminate/support v5.5.37 conflicts with laravel/framework[v5.6.20].
    - illuminate/support v5.5.39 conflicts with laravel/framework[v5.6.20].
    - illuminate/support v5.5.40 conflicts with laravel/framework[v5.6.20].
    - don't install illuminate/support v5.5.33|don't install laravel/framework v5.6.20
    - don't install illuminate/support v5.5.34|don't install laravel/framework v5.6.20
    - Installation request for laravel/framework (locked at v5.6.20, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.20].

Installation failed, reverting ./composer.json to its original content.

How can I resolve this problem?

**Comment by mcnamee** [comment]
Hi @protected22 
That one is a composer error caused by unmet dependencies.

Double check that your current project meets the dependency requirements ([composer.json](https://github.com/pvtl/voyager-frontend/blob/master/composer.json)) for Voyager Frontend - also keep in mind that we're locked to Voyager 1.0.x at the moment which does not support Laravel 5.6 yet.

**Comment by protected22** [comment]
maybe then is the Voyager version the problem because I use the most recent one. How can I downgrade to  Voyager 1.0.x?

**Comment by mcnamee** [comment]
@protected22 I'm not 100%. You could try changing your `composer.json` and `composer install`'ing, although `php artisan voyager:install` does move files, create DB migrations etc - so I don't know if going backwards is possible.

**Comment by bwmadda** [comment]
@protected22 is because you are using Laravel 5.6. You have to use Laravel 5.5. for the voyager-frontend

Best of luck!

**Comment by protected22** [comment]
Now I tried it with Laravel 5.5 and Voyager. 

My cmd log when i used composer require pvtl/voyager-frontend:

C:\Users\Gebruiker\Desktop\php frmework\Laravel Projects\voyager-frontend>compos
er require pvtl/voyager-frontend
Using version ^0.7.0 for pvtl/voyager-frontend
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 18 installs, 0 updates, 0 removals
  - Installing laravel/scout (v4.0.3): Downloading (100%)
  - Installing teamtnt/tntsearch (v1.3.1): Downloading (100%)
  - Installing teamtnt/laravel-scout-tntsearch-driver (v3.0.6): Downloading (con
Downloading (100%)
  - Installing spatie/temporary-directory (1.1.4): Downloading (100%)
  - Installing spatie/phpunit-snapshot-assertions (1.2.1): Downloading (connecti
Downloading (100%)
  - Installing spatie/image-optimizer (1.0.14): Downloading (100%)
  - Installing league/glide (1.3.0): Downloading (100%)
  - Installing spatie/image (1.5.1): Downloading (100%)
  - Installing spatie/browsershot (2.4.2): Downloading (100%)
  - Installing nicmart/tree (v0.2.7): Downloading (100%)
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.3): Downloading (100%)
  - Installing symfony/dom-crawler (v4.0.9): Downloading (100%)
  - Installing spatie/crawler (2.7.1): Downloading (100%)
  - Installing spatie/laravel-sitemap (3.3.1): Downloading (100%)
  - Installing pvtl/voyager-blog (0.1.0): Downloading (100%)
  - Installing pvtl/voyager-pages (0.1.2): Downloading (100%)
  - Installing pvtl/voyager-frontend (0.7.0): Downloading (100%)
laravel/scout suggests installing algolia/algoliasearch-client-php (Required to
use the Algolia engine (^1.10).)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In PageController.php line 10:

  Declaration of Pvtl\VoyagerFrontend\Http\Controllers\PageController::edit(I
  lluminate\Http\Request $request, $id) should be compatible with TCG\Voyager
  \Http\Controllers\VoyagerBreadController::edit($table)


Script @php artisan package:discover handling the post-autoload-dump event retur
ned with error code 1

C:\Users\Gebruiker\Desktop\php frmework\Laravel Projects\voyager-frontend>

What does that error on PageController mean?

**Comment by protected22** [comment]
I think it's the latest version (1.1) because idk how to install an other/previous version of Voyager

**Comment by mcnamee** [comment]
Try the answer from here: https://github.com/pvtl/voyager-frontend/issues/11#issuecomment-386481429
