### ISSUE TITLE
PageController.php

### ISSUE THREAD

**Issue by AlexanderWM** [pvtl/voyager-frontend#12]
In PageController.php line 10:

  Declaration of Pvtl\VoyagerFrontend\Http\Controllers\PageController::edit(Illuminate\Http\Request $request, $id) should be
  compatible with TCG\Voyager\Http\Controllers\VoyagerBreadController::edit($table)

**Comment by Jean-PierreGassin** [comment]
Hey @AlexanderWM,

Check this issue out #10 - seems like you're running an un-supported version of Voyager at the moment.

**Comment by Jean-PierreGassin** [comment]
Hey @AlexanderWM,

Just writing to inform you that we've updated our modules to support Voyager 1.1 and Laravel 5.6 - if you could update and post back with your results that'd be great 👍
