### ISSUE TITLE
made blog posts, but none of them are shown on website pages?

### ISSUE THREAD

**Issue by protected22** [pvtl/voyager-frontend#13]
Hi.  I had made some blogposts. but none of them are getting showed on the home page or on the blog page

**Comment by Jean-PierreGassin** [comment]
Hey @protected22,

Just so I can debug a little more, can I grab the following info:

* What is the URL you're navigating to for the blog posts?
* What version of Voyager and Voyager Frontend are you running?

**Comment by mcnamee** [comment]
Hi @protected22 
I think you may need to install the [voyager-blog](https://github.com/pvtl/voyager-blog#installation) module in order to view blog articles on the front-end

**Comment by protected22** [comment]
- @Jean-PierreGassin 
I tried from http://127.0.0.1:8000/   and  http://127.0.0.1:8000/blog
versions:
"laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0",
        "pvtl/voyager-frontend": "^0.7.0",
        "pvtl/voyager-pages": "^0.1.2",
        "tcg/voyager": "1.0.17"

**Comment by protected22** [comment]
@mcnamee   okay then i'll do that

**Comment by Jean-PierreGassin** [comment]
Hey @protected22,

We've updated our packages just recently to support new versions of Voyager and Laravel (1.1 and 5.6 respectively).

Could you try updating and posting back with your results?

**Comment by protected22** [comment]
I've updated it, still nothing on http://127.0.0.1:8000/blog
![image](https://user-images.githubusercontent.com/20900147/39807926-df15cbde-537d-11e8-9e9d-e4ce8c3eef46.png)

But when i try to make a blogpost I get this error:
Class 'AlgoliaSearch\Version' not found

![image](https://user-images.githubusercontent.com/20900147/39807890-c83797b2-537d-11e8-82f3-be19d5fcb487.png)

**Comment by Jean-PierreGassin** [comment]
@protected22 have you published the post and made it active?

Also RE: AlgoliaSearch, I recommend you read the installation README again :)

**Comment by protected22** [comment]
the post was published and made active using the featured option.

for the installation I followed these steps: https://github.com/pvtl/voyager-frontend/issues/11#issuecomment-386481429

I see nothing about  AlgoliaSearch in the readme. only the search part but that does give the same error

**Comment by Jean-PierreGassin** [comment]
@protected22 make sure you have:

* "SCOUT_DRIVER" setup in your .env file
* composer install'd since updating last

**Comment by protected22** [comment]
looks like that doesn't work anymore. 

when you set SCOUT_DRIVER=tntsearch in .env you get the following error:
Declaration of TeamTNT\Scout\Engines\TNTSearchEngine::map(Laravel\Scout\Builder $builder, $results, $model) must be compatible with Laravel\Scout\Engines\Engine::map($results, $model)
![image](https://user-images.githubusercontent.com/20900147/44221113-c05ce780-a180-11e8-8096-d7fbab9d73b0.png)

**Comment by protected22** [comment]
looks like that doesn't work anymore. 
when you set SCOUT_DRIVER=tntsearch in .env you get the following error:
Declaration of TeamTNT\Scout\Engines\TNTSearchEngine::map(Laravel\Scout\Builder $builder, $results, $model) must be compatible with Laravel\Scout\Engines\Engine::map($results, $model)
