### ISSUE TITLE
Error list while installing the package

### ISSUE THREAD

**Issue by yasser4ever1** [pvtl/voyager-frontend#14]
Hello i am having problem when i used the command `composer require pvtl/voyager-frontend` i received the following error list

![capture](https://user-images.githubusercontent.com/2912056/39787112-02c20f3e-5324-11e8-8756-f07a53803537.JPG)

Any ideas on how to solve this issue ?

**Comment by Jean-PierreGassin** [comment]
Hey @yasser4ever1,

The composer "conclusion" states that you should not be using Laravel 5.6, instead use Laravel 5.5 (as this is what is currently supported).

**Comment by yasser4ever1** [comment]
@Jean-PierreGassin i already have laravel 5.6

![capture](https://user-images.githubusercontent.com/2912056/39787267-d0c6dc20-5324-11e8-922b-9a6e921c3097.JPG)

**Comment by Jean-PierreGassin** [comment]
@yasser4ever1 Please read the above comment, I stated that you should __not__ be using Laravel 5.6 - instead __swap to Laravel 5.5__

**Comment by yasser4ever1** [comment]
@Jean-PierreGassin aha sorry i didn't focus .. could you please let me know how to swap to another version and is it flexible to swap between versions because i am afraid to cause problems from this step

**Comment by Jean-PierreGassin** [comment]
Hey @yasser4ever1,

We've just recently updated the package and others to support Voyager 1.1 and Laravel 5.6 - try updating/re-installing them and post back with your results.
