### ISSUE TITLE
Editing a page from voyager admin throws an exception

### ISSUE THREAD

**Issue by ltheringaud** [pvtl/voyager-frontend#16]
Hi, 
After a click on the edit button:
```
Undefined variable: layouts (View: /<project_path>/vendor/pvtl/voyager-frontend/resources/views/vendor/voyager/pages/edit-add.blade.php) at /<project_path>/storage/framework/views/f80a0286a43dfe1a31c1bd6626c33a06cf2a44e2.php:35, ErrorException(code: 0): Undefined variable: layouts at /<project_path>/storage/framework/views/f80a0286a43dfe1a31c1bd6626c33a06cf2a44e2.php:35)
```

located line 35
```
<?php $__currentLoopData = $layouts; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $layout): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
```

It happened on a fresh install: laravel app + voyager + voyager-frontend

**Comment by Jean-PierreGassin** [comment]
Hey @ltheringaud, what version of Laravel/Voyager/Frontend are you running?

Could you provide some steps to reproduce the issue so that I can thoroughly test it and implement a fix if it's actually an issue?

**Comment by ltheringaud** [comment]
Well I am testing different environments for my project. 

For this test. I was on
Laravel 5.6
Voyager 1.1

On this fresh install just login in the back office and try to add / edit a page then exception thrown.  
Voyager-frontend latest

**Comment by MarcGaumont** [comment]
Same here, fresh install, latest everything... read the installs correctly.
![capture d ecran 2018-06-01 a 5 04 00 pm](https://user-images.githubusercontent.com/8861811/40863437-d1dc33fc-65bd-11e8-9cc3-45048d7cb31f.png)

**Comment by MrBMT** [comment]
@Jean-PierreGassin I've also had the same thing just happen.

Reproduction steps:
- Setup a fresh dev environment (PHP 7.2.6, MariaDB 10.3, NGINX 1.15.0) - I used [Laravel Valet](https://laravel.com/docs/5.6/valet) to do most of this.
- Follow the installation instructions as per https://github.com/pvtl/voyager-frontend
- Login to the voyager admin, go to Pages
- Click Edit for the Home or About page

![screen shot 2018-06-07 at 11 13 35](https://user-images.githubusercontent.com/6931281/41093720-f6a86504-6a43-11e8-94a8-cf8507afb9d6.png)

**Comment by Jean-PierreGassin** [comment]
Thanks @MrBMT, @MarcGaumont, @ltheringaud - I'm looking into this one now and will provide updates on what comes of it.

In the meantime feel free to send a pull-request if I'm not speedy enough and/or if you feel you have a good solution to the issue.
