### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by aozen** [pvtl/voyager-frontend#17]
I have already have some project with voyager. 
I am using laravel 5.5.40,
Voyager: 1.1
and spatie/laravel-sitemap: 3.3.1

Laravel 5.5 is not support spatie/sitemap 5.2, i am using 3.3.1
voyager-frontend is want sitemap 5.2 
if i made it 5.2 i need to up laravel 5.5 to 5.6 and voyager is not working. Because it want 5.5.* (max)
if im not use 5.2 voyager-frontend isn't working. 

How can i get this paradox and install voyager-frontend successfully? Any tip would be great. Thanks in advance.

**Comment by osmanzeki** [comment]
I can confirm that the upgrade of laravel-sitemap broke backwards compatibility with Laravel 5.5. Upon installation, voyager-frontend now requires Laravel 5.6.

**Comment by aozen** [comment]
Yes, that occurs another problem. Voyager can't run on 5.6 :(
