### ISSUE TITLE
Installing Voyager fronrend

### ISSUE THREAD

**Issue by Chuthi** [pvtl/voyager-frontend#18]
Hello,
am new to laravel  and voyager and I got the following while installing the frontend using windows 10

Your requirements could not be resolved to an installable set of packages.

To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by Stretsh** [comment]
This means that you need to enable the mentioned extensions in your Apache. Check the XAMPP documentation for instructions.

**Comment by mcnamee** [comment]
Thanks for helping @Stretsh - I'll close this due to inactivity
