### ISSUE TITLE
Menu items only nest one level deep

### ISSUE THREAD

**Issue by Jean-PierreGassin** [pvtl/voyager-frontend#2]
The menu builder navigational items are only rendering one level deep and remove any subsequent items that are further down the tree, example:

```
- Root Item
   - Second Item
   - Third Item
      - Fourth Item (Does not render)
```

We should be recursively rendering menu items down the tree and put a soft-limit to how deep it will render (perhaps 3/4 levels is a good place to start)

**Comment by fletch3555** [comment]
If/when you fix this, please PR it to Voyager as well.  We haven't had a chance to resolve it on our side either.  We do render the menu recursively, but the JS functionality to expand the menu entries doesn't work that deep.

**Comment by Jean-PierreGassin** [comment]
Hey @fletch3555,

I've implemented this in the front-end module to be a maximum of 3 levels deep at the moment however I think the nesting you're referring to is for the admin area menu items?

I can definitely take a look into it and submit a PR, however this nesting issue was just for the front-end module.
