### ISSUE TITLE
Your Requirments could not be resolved

### ISSUE THREAD

**Issue by mitismirza** [pvtl/voyager-frontend#20]
hey guys
i'm using : 
laravel  5.6.26
PHP Version 7.2.0

i installed the voyager and i want to install the voyager-frontend and when i run : 
` composer require pvtl/voyager-frontend  `
![image](https://user-images.githubusercontent.com/11253027/42408946-21b064a2-81e8-11e8-9391-b961f3d75368.png)

plz help

**Comment by Stretsh** [comment]
This means that you need to enable the mentioned extensions in your Apache. The sqlite3 extension in your case.
