### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by trippo** [pvtl/voyager-frontend#23]
on php artisan voyager-frontend:install

` Symfony\Component\Process\Exception\ProcessFailedException  : The command "
            npm i foundation-sites scrollreveal motion-ui jquery --save-dev &&
            npm uninstall bootstrap bootstrap-sass --save-dev &&
            npm run dev
        " failed.

Exit Code: 1(General error)

Working directory: /Users/alberto/Sites/test

Output:
================
+ jquery@3.3.1
+ scrollreveal@3.4.0
+ foundation-sites@6.5.0-rc.2
+ motion-ui@2.0.3
added 4 packages from 4 contributors and audited 4 packages in 1.772s
found 0 vulnerabilities

Error Output:
================
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN foundation-sites@6.5.0-rc.2 requires a peer of what-input@>=4.1.0 but none is installed. You must install peer dependencies yourself.

npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

  at /Users/alberto/Sites/test/vendor/symfony/process/Process.php:223
    219|      */
    220|     public function mustRun(callable $callback = null, array $env = array())
    221|     {
    222|         if (0 !== $this->run($callback, $env)) {
  > 223|             throw new ProcessFailedException($this);
    224|         }
    225| 
    226|         return $this;
    227|     }

  Exception trace:

  1   Symfony\Component\Process\Process::mustRun()
      /Users/alberto/Sites/test/vendor/pvtl/voyager-frontend/src/Commands/InstallCommand.php:97

  2   Pvtl\VoyagerFrontend\Commands\InstallCommand::handle(Object(Illuminate\Filesystem\Filesystem))
      /Users/alberto/Sites/test/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29

  Please use the argument -v to see more details.`

**Comment by mcnamee** [comment]
Hi @trippo 
Looks like it's an NPM issue. Unfortunately I can't replicate. What version of Node and NPM are you running?

I'm on:

```
➜  ~ node -v
v10.6.0
➜  ~ npm -v
6.2.0
```

**Comment by trippo** [comment]
node v8.9.4
ppm 6.2.0

**Comment by mcnamee** [comment]
Hi @trippo 
I believe @lukewmoore fixed this with v0.8.3
Can you please confirm?

**Comment by lukewmoore** [comment]
I can't replicate the issue using npm 6.2.0, I believe this issue is related to the local npm installation and not voyager-frontend. You can try running `npm cache clean --force` to reset the npm cache before running `php artisan voyager-frontend:install` to see if that helps.
