### ISSUE TITLE
Disable default routes

### ISSUE THREAD

**Issue by zeroiszero** [pvtl/voyager-frontend#24]
When this packages come with some default routes like {slug}, blog, register...etc

How can i disable them ?  

using this seems like not reliable:
Route::setRoutes(new Illuminate\Routing\RouteCollection);
Source: https://laracasts.com/discuss/channels/laravel/remove-vendor-routes-from-route-list?page=0

**Comment by mcnamee** [comment]
Hey @zeroiszero 
Keen for you to submit a PR to make this more dynamic and resolve the issue you're facing. Thanks for raising.
