### ISSUE TITLE
Images not correct url?

### ISSUE THREAD

**Issue by protected22** [pvtl/voyager-frontend#25]
Hi. 

Ive succesfully installed Voyager Frontend. But I get an new problem

Image urls are incorrect. 
I get http://localhost/storage/resized/-260x175/log_posts/July2018/3IuZHemFYyJvv9RkgUUK.png instead of  https://watkanjedoentegenhackers.nl/storage/app/public/resized/-260x175/log_posts/July2018/3IuZHemFYyJvv9RkgUUK.png

**Comment by mcnamee** [comment]
Hi @protected22 

The hostname is assigned from the `APP_URL` variable in your `.env`.

Alternatively you can also add `ASSET_URL` (to `.env`) if you want to use a different URL from your Laravel App URL (eg. if you wanted to reference images on a CDN).

Let us know if that works

**Comment by protected22** [comment]
Looks like changing it from localhost to https://watkanjedoentegenhackers.nl/public doesn't work. It still thinks the image is on  http://localhost/storage/resized/-260x175/log_posts/July2018/3IuZHemFYyJvv9RkgUUK.png

**Comment by lukewmoore** [comment]
@protected22 can you confirm what your `APP_URL` and `ASSET_URL` are set to and what exactly is being output if you're still having issues with this?

**Comment by protected22** [comment]
After I made a fresh installation, the problem got solved. The APP_URL and ASSER_URL are both set to https://watkanjedoentegenhackers.nl/public/
