### ISSUE TITLE
can't make, edit or delete pages

### ISSUE THREAD

**Issue by protected22** [pvtl/voyager-frontend#26]
I can't do anything on the pages part on the admin panel.

Error when I try to edit a page:
![image](https://user-images.githubusercontent.com/20900147/43370577-aadb2780-9381-11e8-9a43-f13ad7bf5d5b.png)

Error when I try to create a page:
![image](https://user-images.githubusercontent.com/20900147/43370588-e0f53ebe-9381-11e8-9efd-5a91cc260e04.png)

**Comment by mcnamee** [comment]
Hi @protected22

Can you please let us know what version you're running for:

- Laravel
- Voyager
- Voyager  Frontend

**Comment by protected22** [comment]
"php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "^1.0",
        "pvtl/voyager-blog": "^0.2.1",
        "pvtl/voyager-frontend": "^0.8.1",
        "pvtl/voyager-pages": "^0.2.0",
        "tcg/voyager": "^1.1"

**Comment by mcnamee** [comment]
Hey @protected22 
Would you mind installing fresh with the latest:

- "pvtl/voyager-frontend": "^0.8.__2__",
- "pvtl/voyager-blog": "^0.2.__3__",
- "pvtl/voyager-pages": "^0.2.__5__",

To see if that helps.

**Comment by protected22** [comment]
By doing Composer update in my cmd?

**Comment by protected22** [comment]
I've used Composer Update, but looks like its still on this: 

"laravel/framework": "5.6.*",
        "laravel/tinker": "^1.0",
        "pvtl/voyager-blog": "^0.2.1",
        "pvtl/voyager-frontend": "^0.8.1",
        "pvtl/voyager-pages": "^0.2.0",
        "tcg/voyager": "^1.1"

**Comment by protected22** [comment]
@mcnamee Do you know how I can update to the versions you mentioned? Looks like composer update didn't work

**Comment by protected22** [comment]
When i try to install the frontend version 0.8.2 I get the following error:

C:\Users\Gebruiker\Desktop\php frmework\Laravel Projects\Voyager-frontend_new>composer require pvtl/voyager-frontend:0.8.2
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for pvtl/voyager-frontend 0.8.2 -> satisfiable by pvtl/voyager-frontend[0.8.2].
    - Conclusion: remove laravel/framework v5.5.42
    - Conclusion: don't install laravel/framework v5.5.42
    - pvtl/voyager-frontend 0.8.2 requires spatie/laravel-sitemap ~5.2.0 -> satisfiable by spatie/laravel-sitemap[5.2.0, 5.2.1].
    - spatie/laravel-sitemap 5.2.0 requires spatie/crawler ^4.1.0 -> satisfiable by spatie/crawler[4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7].
    - spatie/laravel-sitemap 5.2.1 requires spatie/crawler ^4.1.0 -> satisfiable by spatie/crawler[4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7].
    - spatie/crawler 4.1.0 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.27, v5.6.28, v5.6.29, v5.
6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9]
.
    - spatie/crawler 4.1.1 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.27, v5.6.28, v5.6.29, v5.
6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9]
.
    - spatie/crawler 4.1.2 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.27, v5.6.28, v5.6.29, v5.
6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9]
.
    - spatie/crawler 4.1.3 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.27, v5.6.28, v5.6.29, v5.
6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9]
.
    - spatie/crawler 4.1.4 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.27, v5.6.28, v5.6.29, v5.
6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9]
.
    - spatie/crawler 4.1.5 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.27, v5.6.28, v5.6.29, v5.
6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9]
.
    - spatie/crawler 4.1.6 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.27, v5.6.28, v5.6.29, v5.
6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9]
.
    - spatie/crawler 4.1.7 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.27, v5.6.28, v5.6.29, v5.
6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9]
.
    - don't install illuminate/support v5.6.0|don't install laravel/framework v5.5.42
    - don't install illuminate/support v5.6.1|don't install laravel/framework v5.5.42
    - don't install illuminate/support v5.6.2|don't install laravel/framework v5.5.42
    - don't install illuminate/support v5.6.3|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.0|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.11|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.12|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.13|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.14|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.15|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.16|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.17|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.18|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.19|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.20|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.21|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.22|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.23|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.24|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.25|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.27|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.28|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.29|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.30|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.31|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.32|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.33|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.4|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.5|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.6|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.7|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.8|don't install laravel/framework v5.5.42
    - don't install tightenco/collect v5.6.9|don't install laravel/framework v5.5.42
    - Installation request for laravel/framework (locked at v5.5.42, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.42].


Installation failed, reverting ./composer.json to its original content.

C:\Users\Gebruiker\Desktop\php frmework\Laravel Projects\Voyager-frontend_new>

**Comment by protected22** [comment]
Ive made a fresh installation with the latest versions.
After starting the webserver using php artisan serve i get an error:
Argument 2 passed to Symfony\Component\HttpFoundation\Request::setTrustedProxies() must be of the type integer, array given, called in C:\Users\Gebruiker\Desktop\php frmework\Laravel Projects\Voyager-frontend_new\vendor\fideloper\proxy\src\TrustProxies.php on line 54
![image](https://user-images.githubusercontent.com/20900147/44216687-c9948700-a175-11e8-8b75-f7bb21fb30f7.png)

**Comment by lukewmoore** [comment]
@protected22 Your fideloper/proxy package appears to be out of date. Laravel 5.6 requires the $headers property in App\Http\Middleware\TrustProxies to be set to a bit property. If you're using Laravel 5.6, you need to make sure you're using `"fideloper/proxy": "^4.0"` in your composer.json.

**Comment by protected22** [comment]
Okay i've done that, But now I get some new errors and things:

the first one is this: A script code on every page on the footer. 
![image](https://user-images.githubusercontent.com/20900147/44250720-cfca4800-a1f5-11e8-9915-df11475e8df9.png)

Other thing is, I can make pages and posts. but I get this error every time: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry
![image](https://user-images.githubusercontent.com/20900147/44250850-71ea3000-a1f6-11e8-90de-284df9649e53.png)

page error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'meta_keywords' in 'field list' (SQL: insert into `pages` (`title`, `excerpt`, `body`, `slug`, `meta_description`, `meta_keywords`, `status`, `image`, `author_id`, `updated_at`, `created_at`) values (test page, exerp text, <p>body text</p>, test-page, m,eta text, keyword, ACTIVE, pages\August2018\K9vp6jy0BxvaVXJwwX8X.jpg, 1, 2018-08-17 06:25:16, 2018-08-17 06:25:16))
![image](https://user-images.githubusercontent.com/20900147/44251018-2a17d880-a1f7-11e8-833b-989dcde55471.png)

Also when I try to change the site logo in the voyager dashboard settings I get this error:
Declaration of TeamTNT\Scout\Engines\TNTSearchEngine::map(Laravel\Scout\Builder $builder, $results, $model) must be compatible with Laravel\Scout\Engines\Engine::map($results, $model)
![image](https://user-images.githubusercontent.com/20900147/44251062-57fd1d00-a1f7-11e8-9c1a-ebdbfd4f772d.png)
