### ISSUE TITLE
Image thumbnail generator

### ISSUE THREAD

**Issue by mcnamee** [pvtl/voyager-frontend#3]
Voyager currently gives path to the full image. It'd be great if we can pass that URL/path to a method along with a size, and the output to the front-end would be a cropped/sized/cached image.

**Comment by Jean-PierreGassin** [comment]
Hey @mcnamee have you seen this: https://voyager.readme.io/docs/thumbnails-url - looks like you can do this with Voyager's Helper methods, creating thumbnails and then outputting them to the front-end.
