### ISSUE TITLE
some other issues I got. 

### ISSUE THREAD

**Issue by protected22** [pvtl/voyager-frontend#31]
Because my old issue post (https://github.com/pvtl/voyager-frontend/issues/26)  got closed, I'll go on here: 
I got some errors after using "fideloper/proxy": "^4.0" in my composer.json.

the first one is this: A script code on every page on the footer. 
![image](https://user-images.githubusercontent.com/20900147/44250720-cfca4800-a1f5-11e8-9915-df11475e8df9.png)

Other thing is, I can make pages and posts. but I get this error every time: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry
![image](https://user-images.githubusercontent.com/20900147/44250850-71ea3000-a1f6-11e8-90de-284df9649e53.png)

page error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'meta_keywords' in 'field list' (SQL: insert into `pages` (`title`, `excerpt`, `body`, `slug`, `meta_description`, `meta_keywords`, `status`, `image`, `author_id`, `updated_at`, `created_at`) values (test page, exerp text, <p>body text</p>, test-page, m,eta text, keyword, ACTIVE, pages\August2018\K9vp6jy0BxvaVXJwwX8X.jpg, 1, 2018-08-17 06:25:16, 2018-08-17 06:25:16))
![image](https://user-images.githubusercontent.com/20900147/44251018-2a17d880-a1f7-11e8-833b-989dcde55471.png)

Also when I try to change the site logo in the voyager dashboard settings I get this error:
Declaration of TeamTNT\Scout\Engines\TNTSearchEngine::map(Laravel\Scout\Builder $builder, $results, $model) must be compatible with Laravel\Scout\Engines\Engine::map($results, $model)
![image](https://user-images.githubusercontent.com/20900147/44251062-57fd1d00-a1f7-11e8-9c1a-ebdbfd4f772d.png)

**Comment by lukewmoore** [comment]
Hi @protected22 

The script tag in the footer, meta_keywords and Scout issues have all been fixed as of 0.8.3.

The duplicate slug issues have now been fixed in voyager-blog 0.2.4 and voyager-pages 0.2.7. You can also edit the BREAD for blog_posts and pages manually from within the Voyager backend if you have already run `voyager-frontend:install`.

Go to Tools > BREAD and edit the blog_posts table. For the slug field, under Optional Details, add "validation" to the object underneath "slugify".

```json
{
    "slugify": {
        "origin": "title",
        "forceUpdate": true
    },
    "validation": {
        "rule": "unique:blog_posts,slug"
    }
}
```

Save it and now when saving posts it will validate correctly. You should do the same for pages, just change the blog_posts to pages in the validation rule.

**Comment by protected22** [comment]
I've tried to update Voyager-frontend to 0.8.3 but it failed because it requires scout ^5.0.  but I can't update to ^5,0 because of an error: 

C:\Users\Gebruiker\Desktop\php frmework\Laravel Projects\Voyager-frontend_new>composer require pvtl/voyager-frontend 
Using version ^0.8.3 for pvtl/voyager-frontend
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for pvtl/voyager-frontend ^0.8.3 -> satisfiable by pvtl/voyager-frontend[0.8.3].
    - pvtl/voyager-frontend 0.8.3 requires laravel/scout ^5.0 -> satisfiable by laravel/scout[5.0.x-dev, v5.0.0, v5.0.1, v5.0.2, v5.0.3] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.

C:\Users\Gebruiker\Desktop\php frmework\Laravel Projects\Voyager-frontend_new>composer require laravel/scout
Using version ^5.0 for laravel/scout
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pvtl/voyager-frontend 0.8.2 requires laravel/scout ^4.0 -> satisfiable by laravel/scout[4.0.x-dev, v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4] but these conflict with your requirements or minimum-stability.
    - pvtl/voyager-frontend 0.8.2 requires laravel/scout ^4.0 -> satisfiable by laravel/scout[4.0.x-dev, v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4] but these conflict with your requirements or minimum-stability.
    - pvtl/voyager-frontend 0.8.2 requires laravel/scout ^4.0 -> satisfiable by laravel/scout[4.0.x-dev, v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4] but these conflict with your requirements or minimum-stability.
    - Installation request for pvtl/voyager-frontend 0.8.2 -> satisfiable by pvtl/voyager-frontend[0.8.2].


Installation failed, reverting ./composer.json to its original content.

C:\Users\Gebruiker\Desktop\php frmework\Laravel Projects\Voyager-frontend_new>

**Comment by lukewmoore** [comment]
If you have scout in your composer.json try removing it or make sure you require ^5.0. Then you can run `composer update pvtl/voyager-frontend`. Your trying to require either packages individually appears to be clashing

**Comment by protected22** [comment]
Got the same error. I've also changed it in the composer.lock file. 




First try was only changing the version of Scout from 4.0.* to ^5.0 in composer.json:

C:\Users\Gebruiker\Desktop\php frmework\Laravel Projects\Voyager-frontend_new>composer update pvtl/voyager-frontend
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package laravel/scout (locked at v4.0.4, required as ^5.0) is satisfiable by laravel/scout[v4.0.4] but these conflict with your requirements or minimum-stability.
  Problem 2
    - pvtl/voyager-frontend 0.8.2 requires laravel/scout ^4.0 -> satisfiable by
laravel/scout[4.0.x-dev, v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4] but these conflict with your requirements or minimum-stability.
    - pvtl/voyager-frontend 0.8.2 requires laravel/scout ^4.0 -> satisfiable by
laravel/scout[4.0.x-dev, v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4] but these conflict with your requirements or minimum-stability.
    - pvtl/voyager-frontend 0.8.2 requires laravel/scout ^4.0 -> satisfiable by
laravel/scout[4.0.x-dev, v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4] but these conflict with your requirements or minimum-stability.
    - Installation request for pvtl/voyager-frontend 0.8.2 -> satisfiable by pvtl/voyager-frontend[0.8.2].

next try was changing the scout version in composer.lock to 5.0:
C:\Users\Gebruiker\Desktop\php frmework\Laravel Projects\Voyager-frontend_new>composer update pvtl/voyager-frontend
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pvtl/voyager-frontend 0.8.2 requires laravel/scout ^4.0 -> satisfiable by
laravel/scout[4.0.x-dev, v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4] but these conflict with your requirements or minimum-stability.
    - pvtl/voyager-frontend 0.8.2 requires laravel/scout ^4.0 -> satisfiable by
laravel/scout[4.0.x-dev, v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4] but these conflict with your requirements or minimum-stability.
    - pvtl/voyager-frontend 0.8.2 requires laravel/scout ^4.0 -> satisfiable by laravel/scout[4.0.x-dev, v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4] but these conflict with your requirements or minimum-stability.
    - Installation request for pvtl/voyager-frontend 0.8.2 -> satisfiable by pvtl/voyager-frontend[0.8.2].

C:\Users\Gebruiker\Desktop\php frmework\Laravel Projects\Voyager-frontend_new>

**Comment by lukewmoore** [comment]
Closing as original issue has been fixed.
