### ISSUE TITLE
Error when change path for admin

### ISSUE THREAD

**Issue by snggh** [pvtl/voyager-frontend#34]
I want to change the default prefix admin route from www.mysite.com/admin to www.mysite.com. 

In routes/web.php I added:

`Voyager::routes();`

And in config/voyager.php I change : 

`'redirect' => '/admin',`

to:

`'redirect' => '/',`

But give me the following error:

![image](https://user-images.githubusercontent.com/9331718/46590424-58ba7d00-cadd-11e8-82b5-e885c8a6cf98.png)

Laravel Version: **5.7.6**
Voyager Version: **1.1**
Voyager Frontend Version: **0.8.3**
PHP Version: **7.1.7**

**Comment by lukewmoore** [comment]
@snggh this is overriding the default login route /login. You can update the Voyager Frontend views with the appropriate Voyager routes, or override the Voyager routes from the defaults. See the [Voyager docs](https://voyager.readme.io/docs/overriding-routes).
