### ISSUE TITLE
Voyager >= 1.1.8 casts row-details automatically

### ISSUE THREAD

**Issue by emptynick** [pvtl/voyager-frontend#35]
Hello,

With Voyager version >= 1.18 the `DataRow` model was changed to directly return the `details` as an array, not as a json-encoded string https://github.com/the-control-group/voyager/pull/3637.
This causes some errors with your package, for example
https://github.com/the-control-group/voyager/issues/3656#issuecomment-431578041

Until its fixed here, users should stick to Voyager version 1.1.7

Christoph

**Comment by tommiekn** [comment]
@mcnamee @emptynick @superhaggis @wireblue @CiaranR Hi, not sure if you saw this issue, It is a blocking issue that should be fixed asap or we can't update to latest version. Could someone give it a check?

**Comment by wireblue** [comment]
Hi @emptynick and @tommiekn. This should have been resolved in this commit (https://github.com/pvtl/voyager-frontend/commit/aaa136e10055b09f78e62334e6c5e9a1d963c998).

Let me know if we can close this issue.

**Comment by emptynick** [comment]
I'm not using voyager-frontend, we just had some people having problems in our Slack-group, so I thought I might tell you guys that we changed this part.
Closing this one.
