### ISSUE TITLE
Admin panel under menu Users gives error

### ISSUE THREAD

**Issue by FrankyJust** [pvtl/voyager-frontend#36]
### Version information
Laravel 5.6.33
Voyager 1.1.9
Voyager Frontend latest version
PHP 7.1.16
MySQL 5.7.21

### Details
When I click in Admin on menu Users following error appears:

json_decode() expects parameter 1 to be string, object given (View: /Users/user/Laravel-CMS/la_voyager/vendor/pvtl/voyager-frontend/resources/views/vendor/voyager/users/browse.blade.php)

**Comment by romontj** [comment]
I have the same error.

**Comment by romontj** [comment]
The _getDetailsAttribute_ method in the DataRow model already uses _json_decode_ on the details attribute.  To resolve I changed line 90 of browse.blade.php from 
`<?php $options = json_decode($row->details); ?>`
to
`<?php $options = $row->details; ?>`

**Comment by lukewmoore** [comment]
Hi @FrankyJust this has been fixed in 0.8.4.
