### ISSUE TITLE
voyager-frontend - footer social media icons

### ISSUE THREAD

**Issue by MTAMAC** [pvtl/voyager-frontend#38]
Before making my query, I want to thank the development work for voyager-frontend

I have a problem with the social media icons in the footer.
I changed the icon "<i> </ i>" in a svg, in principle I should not mind, but I want to modify the icon because it comes out as a box and is not the design I have to do.

Anyone who can help me ?, I searched the archives and I have not located the code

Thanks

**Comment by mcnamee** [comment]
Hi @MTAMAC 
The social media menu:
- Is manageable in Voyager Admin > Tools > Menu > Social (note that in our example, each item has a class referencing a font-awesome icon)
- Code can be found in the [resources/views/partials/social.blade.php](https://github.com/pvtl/voyager-frontend/blob/master/resources/views/partials/social.blade.php)
