### ISSUE TITLE
all your package not install under valet

### ISSUE THREAD

**Issue by cotiga** [pvtl/voyager-frontend#39]
NPM Error, Migration errors, syntax error...
I don't know what append , but nothing go right with PVTL packages

**Comment by mcnamee** [comment]
Hi @cotiga 
I'd recommend that you debug an issue one by one and either:
- Provide helpful information about specific errors (eg. On running command ABC, Voyager Frontend gives error XYZ which looks to be caused by NPM vX.x)
- Submit a PR to resolve
