### ISSUE TITLE
There are no commands defined in the "voyager-frontend" namespace

### ISSUE THREAD

**Issue by scottmcdhome** [pvtl/voyager-frontend#4]
Laravel 5.4
Voyager works without error.

Following your installation instructions I got this message.
C:\wamp\www\voyagerfe>php artisan voyager-frontend:install

  There are no commands defined in the "voyager-frontend" namespace.

**Comment by mcnamee** [comment]
Hi @scottmcdhome 

- Did you run the [Installation](https://github.com/facebook/react/issues/10441#issuecomment-368510525) steps from step 1?
- Does the `/vendor/pvtl/voyager-frontend` directory exist in your repo?
- If you open up `vendor/composer/autoload_classmap.php` and search for `Pvtl\\VoyagerFrontend\\Commands\\InstallCommand` - does the command exist?
