### ISSUE TITLE
 Trait 'TCG\Voyager\Traits\HasRelationships' not found

### ISSUE THREAD

**Issue by ravibhoraniya** [pvtl/voyager-frontend#41]
i install this library but error getting

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
PHP Fatal error:  Trait 'TCG\Voyager\Traits\HasRelationships' not found in /var/www/html/laravel/technique/vendor/pvtl/voyager-pages/src/Page.php on line 12

In Page.php line 12:
                                                         
  Trait 'TCG\Voyager\Traits\HasRelationships' not found

**Comment by mcnamee** [comment]
This has been resolved in the latest release

**Comment by i-kk** [comment]
Which one? I have the same issue with 0.8.5
