### ISSUE TITLE
Can't set active or inactive new pages or blog entries

### ISSUE THREAD

**Issue by Fosphatic** [pvtl/voyager-frontend#42]
To whome it may concern,

This project is very interesting for many purposes, however I'm facing an issue after installation, that when I add new pages or blog entries i can't set them to active anymore.

reagards

fossy

**Comment by Liam-PVTL** [comment]
Hi @Fosphatic. Thanks for your comment - are you still experiencing this issue? 

As far as I can tell it's not reproducible - this may be a result of updating dependencies since Feb of last year. Closing until hearing otherwise.
