### ISSUE TITLE
cant install voyage-frontend

### ISSUE THREAD

**Issue by doctornasty** [pvtl/voyager-frontend#43]
Problem 1
    - Installation request for pvtl/voyager-frontend ^0.8.5 -> satisfiable by pvtl/voyager-frontend[0.8.5].
    - Conclusion: remove laravel/framework v5.5.45
    - Conclusion: don't install laravel/framework v5.5.45

**Comment by LuizHenriqueBK** [comment]
I also had the problem executing the command "php artisan voyager-frontend:install"
![screen](https://user-images.githubusercontent.com/30929047/53290063-c958f200-377d-11e9-97de-d10b80bcef4f.png)

PHP version: PHP 7.2.15-0ubuntu0.18.04.1 (cli) (built: Feb  8 2019 14:54:22) ( NTS )
Laravel: Laravel Framework 5.7.27

**Comment by kepman** [comment]
Same problem here, Can't run "php artisan voyager-frontend:install"

PHP 7.1.23 (cli) (built: Nov  7 2018 18:20:35) ( NTS )
NPM 6.7.0
Node v11.12.0

![image](https://user-images.githubusercontent.com/2862907/55046616-c9962700-5074-11e9-9f91-9254a5c2fefc.png)

**Comment by kepman** [comment]
> Same problem here, Can't run "php artisan voyager-frontend:install"
> 
> PHP 7.1.23 (cli) (built: Nov 7 2018 18:20:35) ( NTS )
> NPM 6.7.0
> Node v11.12.0
> Laravel Framework 5.8.8
> ![image](https://user-images.githubusercontent.com/2862907/55046616-c9962700-5074-11e9-9f91-9254a5c2fefc.png)

What worked for me to get the installation going without errors was resetting the cache. Follow these steps:

1: `npm cache clean --force`
2: Remove the node_modules folder
3: Delete package-lock.json
4: `npm install`

**Comment by MajidMohammadpanah** [comment]
D:\majidmohammadpanah>composer require pvtl/voyager-frontend
Using version ^0.9.1 for pvtl/voyager-frontend
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- teamtnt/tntsearch v1.4.0 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
- teamtnt/tntsearch v1.3.6 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
- teamtnt/tntsearch v1.3.5 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
- teamtnt/tntsearch v1.3.4 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
- teamtnt/tntsearch v1.3.3 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
- teamtnt/tntsearch v1.3.2 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
- teamtnt/tntsearch v1.3.1 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
- teamtnt/tntsearch v1.3.0 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
- teamtnt/tntsearch v1.2.0 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
- teamtnt/tntsearch v1.0.7 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
- teamtnt/tntsearch v1.0.6 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
- teamtnt/tntsearch v1.0.5 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
- teamtnt/tntsearch v1.0.4 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
- teamtnt/tntsearch v1.0.3 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
- teamtnt/tntsearch v1.0.2 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
- teamtnt/tntsearch v1.0.1 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
- teamtnt/tntsearch v1.0.0 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
- pvtl/voyager-frontend 0.9.1 requires teamtnt/laravel-scout-tntsearch-driver ^3.0 -> satisfiable by teamtnt/laravel-scout-tntsearch-driver[v3.0.0, v3.
0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.1.0, v3.2.0, v3.2.1, v3.2.2, v3.3.0].
- teamtnt/laravel-scout-tntsearch-driver v3.3.0 requires teamtnt/tntsearch 1.4.* -> satisfiable by teamtnt/tntsearch[v1.4.0].
- teamtnt/laravel-scout-tntsearch-driver v3.0.6 requires teamtnt/tntsearch 1.3.* -> satisfiable by teamtnt/tntsearch[v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1
.3.4, v1.3.5, v1.3.6].
- teamtnt/laravel-scout-tntsearch-driver v3.0.7 requires teamtnt/tntsearch 1.3.* -> satisfiable by teamtnt/tntsearch[v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1
.3.4, v1.3.5, v1.3.6].
- teamtnt/laravel-scout-tntsearch-driver v3.0.8 requires teamtnt/tntsearch 1.3.* -> satisfiable by teamtnt/tntsearch[v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1
.3.4, v1.3.5, v1.3.6].
- teamtnt/laravel-scout-tntsearch-driver v3.1.0 requires teamtnt/tntsearch 1.3.* -> satisfiable by teamtnt/tntsearch[v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1
.3.4, v1.3.5, v1.3.6].
- teamtnt/laravel-scout-tntsearch-driver v3.2.0 requires teamtnt/tntsearch 1.3.* -> satisfiable by teamtnt/tntsearch[v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1
.3.4, v1.3.5, v1.3.6].
- teamtnt/laravel-scout-tntsearch-driver v3.2.1 requires teamtnt/tntsearch 1.3.* -> satisfiable by teamtnt/tntsearch[v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1
.3.4, v1.3.5, v1.3.6].
- teamtnt/laravel-scout-tntsearch-driver v3.2.2 requires teamtnt/tntsearch 1.3.* -> satisfiable by teamtnt/tntsearch[v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1
.3.4, v1.3.5, v1.3.6].
- teamtnt/laravel-scout-tntsearch-driver v3.0.5 requires teamtnt/tntsearch 1.2.* -> satisfiable by teamtnt/tntsearch[v1.2.0].
- teamtnt/laravel-scout-tntsearch-driver v3.0.0 requires teamtnt/tntsearch 1.0.* -> satisfiable by teamtnt/tntsearch[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1
.0.4, v1.0.5, v1.0.6, v1.0.7].
- teamtnt/laravel-scout-tntsearch-driver v3.0.1 requires teamtnt/tntsearch 1.0.* -> satisfiable by teamtnt/tntsearch[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1
.0.4, v1.0.5, v1.0.6, v1.0.7].
- teamtnt/laravel-scout-tntsearch-driver v3.0.2 requires teamtnt/tntsearch 1.0.* -> satisfiable by teamtnt/tntsearch[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1
.0.4, v1.0.5, v1.0.6, v1.0.7].
- teamtnt/laravel-scout-tntsearch-driver v3.0.3 requires teamtnt/tntsearch 1.0.* -> satisfiable by teamtnt/tntsearch[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1
.0.4, v1.0.5, v1.0.6, v1.0.7].
- teamtnt/laravel-scout-tntsearch-driver v3.0.4 requires teamtnt/tntsearch 1.0.* -> satisfiable by teamtnt/tntsearch[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1
.0.4, v1.0.5, v1.0.6, v1.0.7].
- Installation request for pvtl/voyager-frontend ^0.9.1 -> satisfiable by pvtl/voyager-frontend[0.9.1].

To enable extensions, verify that they are enabled in your .ini files:
- C:\xampp\php\php.ini
You can also run php --ini inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

**Comment by mcnamee** [comment]
There's actually 3 different errors in this thread:

- @doctornasty issue is related to not having the correct composer dependencies - i.e. there's a package in your project tree that requires a later (than 5.5.45) version of Laravel (i.e. try installing Laravel 5.7 or 5.8)
- @LuizHenriqueBK issue is a Laravel Mix/NPM issue - which can likely be solved by https://github.com/JeffreyWay/laravel-mix/issues/1072#issuecomment-319401164
- @MajidMohammadpanah issue says that `teamtnt/tntsearch v1.0.0 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system` (i.e. you need the PHP extension sqlite3 installed - as it's required by `tntsearch`) (I've added this to the readme requirements for clarity)
