### ISSUE TITLE
AlgoliaSearch requires an applicationID

### ISSUE THREAD

**Issue by steveadamsfixedit** [pvtl/voyager-frontend#45]
I've created a development site on my stand alone machine and uploaded it to a development server running ubuntu 18.04 with laravel 5.7.27. The local install works perfectly, but I pushed it up, reset the local database, and run composer install and the site comes up HOWEVER, when logging in or out of voyager or trying to make ANY changes, it throws the error: AlgoliaSearch requires an applicationID

Can I reset the search engine somewhere in the code so it uses a different search engine? What about uninstalling scout?

**Comment by steveadamsfixedit** [comment]
I've gone as far as to register with Algolia and put my app ID and secret key into the vendor/laravel/scout/config/scout.php and I still receive the error

**Comment by steveadamsfixedit** [comment]
resolved the issue with app ID and secret in config/scout.php

**Comment by steveadamsfixedit** [comment]
Well...the solution was intermittent...I have the settings for mailtrap in my ENV file and a working Algolia id and key in config/scout.php and and time I click a save settings or edit a page, it causes an error with "AlgoliaSearch requires an applicationID." and points to vendor
/algolia/algoliasearch-client-php/src/AlgoliaSearch/ClientContext.php

**Comment by mcnamee** [comment]
Hi @steveadamsfixedit 
Our recommendation ([instructions here](https://github.com/pvtl/voyager-frontend#installation)) is to use the 'free' `tntsearch` scout/search driver.

Assuming you've installed/set this correctly - you shouldn't need Algolia.
