### ISSUE TITLE
overriding default views

### ISSUE THREAD

**Issue by steveadamsfixedit** [pvtl/voyager-frontend#46]
I notice that the views in vendor/pvtl/voyager-frontend/resources/views/ are not commonly synced when using GIT to deploy a site. Rather, the whole folder is ignored in the .gitignore file. Would it not benefit the project to copy this folder to the public/vendor or ./resources/views folder?

What would be your suggested method for overriding this folder so that it doesn't get overwritten with and source update?

**Comment by eddielee394** [comment]
Not sure exactly what you're asking, but the package does allow you to override (and version control if you choose) the default vendor views.  
https://github.com/pvtl/voyager-frontend#overriding-views

**Comment by steveadamsfixedit** [comment]
Thank you, you resolved my issue. Starting a new one for further exploration of the override
