### ISSUE TITLE
possible to override just the /home route with a custom controller?

### ISSUE THREAD

**Issue by steveadamsfixedit** [pvtl/voyager-frontend#47]
I've created a custom view for my /products via a controller. (http://dev7.oddballsinvitations.net/products)

   This page is generated from a BREAD table on the backend. How would I get this pages content to display on the frontend between the voyager-frontend views for the partial/header and partial footer? 

  Basically, I'm asking how to replace the voyager-pages /home page view with the controller generated /products page and route so that my /products content replaces the "this is the home page" here: http://dev7.oddballsinvitations.net

**Comment by lukewmoore** [comment]
Hi @steveadamsfixedit, you could create a custom view for your controller that extends a voyager-frontend layout. e.g.

```blade
@extends('voyager-frontend::layouts.default')
@section('meta_title', '')
@section('meta_description', '')
@section('page_title', '')

@section('content')
    {{-- Your product code --}}
@endsection
```

And then override the index route to display it as your home page.

```php
Route::get('/', 'ProductController@index');
```

You could also look into https://github.com/pvtl/voyager-page-blocks, which overrides the default voyager-frontend page editor and allows you to include custom controller methods on a page.

**Comment by steveadamsfixedit** [comment]
I managed to write the custom controller and resolve the issue. Many thanks for your help!
