### ISSUE TITLE
Bug in seeder dont recognize validation rules on bread

### ISSUE THREAD

**Issue by giorgosstab** [pvtl/voyager-frontend#48]
![2019-03-13](https://user-images.githubusercontent.com/17095088/54253123-4219c580-4556-11e9-840f-74bf034a8347.png)

wrong validation on seeder tables... change that syntax
'details'      => json_encode([
                    'slugify' => [
                        'origin' => 'name',
                    ],
                ]),
to that syntax:
'details'      => [
                    'slugify' => [
                        'origin' => 'name',
                    ],
                ],
no need json_encode

**Comment by mcnamee** [comment]
Hi @giorgosstab 
Sorry if I'm misunderstanding your intent - but this `voyager-frontend` repo isn't involved with creating any blog bread rules.

I'll close this, but feel free to comment back if I've misunderstood
