### ISSUE TITLE
Dashboard page widget dissappears on install

### ISSUE THREAD

**Issue by steveadamsfixedit** [pvtl/voyager-frontend#51]
Laravel 5.8.9
"pvtl/voyager-frontend": "^0.9.1",
"tcg/voyager": "^1.2"

the config//voyager.php still contains             'TCG\\Voyager\\Widgets\\PageDimmer',

However, the page widget does not show up in the dashboard

**Comment by mcnamee** [comment]
Hi @steveadamsfixedit 
Happy to see a PR if you can track this down, however I can't see that this repo is modifying any widgets.
