### ISSUE TITLE
i dont can install voyager-frontend,Help me

### ISSUE THREAD

**Issue by MajidMohammadpanah** [pvtl/voyager-frontend#52]
D:\majidmohammadpanah>composer require pvtl/voyager-frontend
Using version ^0.9.1 for pvtl/voyager-frontend
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - teamtnt/tntsearch v1.4.0 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.3.6 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.3.5 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.3.4 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.3.3 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.3.2 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.3.1 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.3.0 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.2.0 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.7 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.6 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.5 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.4 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.3 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.2 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.1 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - teamtnt/tntsearch v1.0.0 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.
    - pvtl/voyager-frontend 0.9.1 requires teamtnt/laravel-scout-tntsearch-driver ^3.0 -> satisfiable by teamtnt/laravel-scout-tntsearch-driver[v3.0.0, v3.
0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.1.0, v3.2.0, v3.2.1, v3.2.2, v3.3.0].
    - teamtnt/laravel-scout-tntsearch-driver v3.3.0 requires teamtnt/tntsearch 1.4.* -> satisfiable by teamtnt/tntsearch[v1.4.0].
    - teamtnt/laravel-scout-tntsearch-driver v3.0.6 requires teamtnt/tntsearch 1.3.* -> satisfiable by teamtnt/tntsearch[v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1
.3.4, v1.3.5, v1.3.6].
    - teamtnt/laravel-scout-tntsearch-driver v3.0.7 requires teamtnt/tntsearch 1.3.* -> satisfiable by teamtnt/tntsearch[v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1
.3.4, v1.3.5, v1.3.6].
    - teamtnt/laravel-scout-tntsearch-driver v3.0.8 requires teamtnt/tntsearch 1.3.* -> satisfiable by teamtnt/tntsearch[v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1
.3.4, v1.3.5, v1.3.6].
    - teamtnt/laravel-scout-tntsearch-driver v3.1.0 requires teamtnt/tntsearch 1.3.* -> satisfiable by teamtnt/tntsearch[v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1
.3.4, v1.3.5, v1.3.6].
    - teamtnt/laravel-scout-tntsearch-driver v3.2.0 requires teamtnt/tntsearch 1.3.* -> satisfiable by teamtnt/tntsearch[v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1
.3.4, v1.3.5, v1.3.6].
    - teamtnt/laravel-scout-tntsearch-driver v3.2.1 requires teamtnt/tntsearch 1.3.* -> satisfiable by teamtnt/tntsearch[v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1
.3.4, v1.3.5, v1.3.6].
    - teamtnt/laravel-scout-tntsearch-driver v3.2.2 requires teamtnt/tntsearch 1.3.* -> satisfiable by teamtnt/tntsearch[v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1
.3.4, v1.3.5, v1.3.6].
    - teamtnt/laravel-scout-tntsearch-driver v3.0.5 requires teamtnt/tntsearch 1.2.* -> satisfiable by teamtnt/tntsearch[v1.2.0].
    - teamtnt/laravel-scout-tntsearch-driver v3.0.0 requires teamtnt/tntsearch 1.0.* -> satisfiable by teamtnt/tntsearch[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1
.0.4, v1.0.5, v1.0.6, v1.0.7].
    - teamtnt/laravel-scout-tntsearch-driver v3.0.1 requires teamtnt/tntsearch 1.0.* -> satisfiable by teamtnt/tntsearch[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1
.0.4, v1.0.5, v1.0.6, v1.0.7].
    - teamtnt/laravel-scout-tntsearch-driver v3.0.2 requires teamtnt/tntsearch 1.0.* -> satisfiable by teamtnt/tntsearch[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1
.0.4, v1.0.5, v1.0.6, v1.0.7].
    - teamtnt/laravel-scout-tntsearch-driver v3.0.3 requires teamtnt/tntsearch 1.0.* -> satisfiable by teamtnt/tntsearch[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1
.0.4, v1.0.5, v1.0.6, v1.0.7].
    - teamtnt/laravel-scout-tntsearch-driver v3.0.4 requires teamtnt/tntsearch 1.0.* -> satisfiable by teamtnt/tntsearch[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1
.0.4, v1.0.5, v1.0.6, v1.0.7].
    - Installation request for pvtl/voyager-frontend ^0.9.1 -> satisfiable by pvtl/voyager-frontend[0.9.1].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

**Comment by mcnamee** [comment]
That error suggests:

```
teamtnt/tntsearch v1.4.0 requires ext-sqlite3 * and the PHP extension sqlite3 is missing from your system.
```

i.e. enabling the PHP extension sqlite3 should fix the issue.

I believe it's used by Laravel Scout as the search driver.

If this fixes, can you please submit a PR to add SQLite3 PHP Extension to the [Prerequisites](https://github.com/pvtl/voyager-frontend#prerequisites)?

**Comment by ankitchauhan22** [comment]
Follow the instructions mentioned in below link:

https://stackoverflow.com/questions/12492908/sqlite-does-not-work-on-localhost-in-windows-7-php/29884323#29884323

It works like a charm.
