### ISSUE TITLE
Error while Installing Voyager

### ISSUE THREAD

**Issue by sutharpratik10** [pvtl/voyager-frontend#54]
### **I am getting database migration error while using the  "php artisan voyager:install --with-dummy" command**
![image](https://user-images.githubusercontent.com/10793403/56471401-abeb9000-646f-11e9-8ec4-6655ba885f86.png)
Pratik@Pratikbhai MINGW64 /d/Pratik/Work/project ultron/ultron_admin/voyager
$ php artisan voyager:install --with-dummy
Publishing the Voyager assets, database, and config files
Copied Directory [\vendor\tcg\voyager\publishable\database\seeds] To [\database\seeds]
Publishing complete.
Publishing complete.
Migrating the database tables into your application
Migrating: 2017_01_14_005015_create_translations_table

   Illuminate\Database\QueryException  : SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'translations' already exists (SQL: create table `translations` (`id` int unsigned not n
ull auto_increment primary key, `table_name` varchar(191) not null, `column_name` varchar(191) not null, `foreign_key` int unsigned not null, `locale` varchar(191) not null, `value` text not n
ull, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at D:\Pratik\Work\project ultron\ultron_admin\voyager\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'translations' already exists")
      D:\Pratik\Work\project ultron\ultron_admin\voyager\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:119

  2   PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'translations' already exists")
      D:\Pratik\Work\project ultron\ultron_admin\voyager\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:117

  Please use the argument -v to see more details.

### **I got this error after editing AppServiceProvider.php file with this below code**

**Illuminate\Support\Facades\Schema;** 

and 

**public function boot()**
    **{**
            **Schema::defaultStringLength(191);**
    **}**

**Comment by mcnamee** [comment]
Hi @sutharpratik10 
Closing as it looks like you've submitted this to the wrong repo. This is related specifically to `Voyager` not the `voyager-frontend` repo.
