### ISSUE TITLE
New Features to be added

### ISSUE THREAD

**Issue by ankitchauhan22** [pvtl/voyager-frontend#55]
Hi, This is just awesome tool in laravel. I'm very excited to explore it more. You have added so much useful bundles - page-blocks, forms etc.

But there should be more bundles like - 

1. Post Type Manager
2. Social Media
3. Comments
4. Workflow for Content Approval.
5. Slider

Let me know your thoughts.

**Comment by mcnamee** [comment]
Hi @ankitchauhan22 Thanks for your encouragement.

Yep they all sound like great ideas - happy building.
