### ISSUE TITLE
Laravel 5.8 vs voyager-frontend: env() stopped working

### ISSUE THREAD

**Issue by code23-isaac** [pvtl/voyager-frontend#56]
After upgrading to Laravel 5.8 the dotenv expects to use getenv() function instead of env(). 

This makes for example the image URLs to break.

In `vendor/pvtl/voyager-frontend/src/Helpers/ImageResize.php` at line 21 if you change:
`$hostname = env('ASSET_URL', env('APP_URL', 'http://localhost'));` to `$hostname = getenv('ASSET_URL', getenv('APP_URL', 'http://localhost'));` it works again. Otherwise it just falls back to 'http://localhost'.

**Comment by mcnamee** [comment]
Hi @code23-isaac 
Unfortunately I can't reproduce this. I've tried a fresh installation with (composer.json):

```json
{
    "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "pvtl/voyager-frontend": "^0.9.1",
        "pvtl/voyager-pages": "^0.2.9",
        "tcg/voyager": "^1.2"
    },
}
```

And I have `APP_URL=http://voyagerlaravel58.pub.localhost` in my `.env`.

I uploaded an image to the backend Voyager Media, then in a blade template, output that file via:

```
<img src="{{ imageUrl('test-image.png', 100, 200, $config = ['crop' => false, 'quality' => 100] ) ?: '/default.png' }}" />
```

And it successfully resized the image to 100x200 in `/storage⁩/app⁩/public⁩/resized/-100x200` + displayed the correct image:

```html
<img src="http://voyagerlaravel58.pub.localhost/storage/resized/-100x200/test-image.png" />
```

Also note that the `env()` function comes from Laravel (as an alias for `getenv()`).

Is there anything I missed?
