### ISSUE TITLE
The page assests are not loading properly 

### ISSUE THREAD

**Issue by x8Haider** [pvtl/voyager-frontend#59]
Hi,

I have Laravel v 5.8 I have followed all steps as per the documents and went well, the only wrong thing happen is the page doesn't load properly no css or image are appearing, tried to re-install the package again and re-run npm run dev but nothing happened. 

Please help.

**Comment by howdu** [comment]
Works correctly for me... try checking browser error console and check HTML source to see what URL is to load CSS.

**Comment by nroussis** [comment]
Same problem for me. I'm using Laravel Valet on Mac.
Everything loads normally... npm run dev gives no errors.
however no styles appear on page.

**Comment by DaveArm** [comment]
I have styles and looks great, just on pages the images and displaying and 404'ing on inspection. Could I have broke or be missing a symlink to storage or something?

**Comment by Liam-PVTL** [comment]
You can see the (default) attempted import of your CSS at /vendor/pvtl/voyager-frontend/resources/views/partials/meta.blade.php. 

Ensure that your public/css/app.css file exists and is being compiled by Webpack - this should fix the issue, so I'm closing the topic for now.
