### ISSUE TITLE
npm run development throws error

### ISSUE THREAD

**Issue by OliverTempel** [pvtl/voyager-frontend#60]
got error
`events.js:174
      throw er; // Unhandled 'error' event
      ^
`
any hints?

**Comment by adriancampanaro** [comment]
I get the same issue.

**Comment by adriancampanaro** [comment]
I solved it by running
npm install webpack --save
npm install

**Comment by Liam-PVTL** [comment]
> I solved it by running
> npm install webpack --save
> npm install

This should fix this install error. I have updated the readme to reflect such.
