### ISSUE TITLE
laravel/framework v6.0.0

### ISSUE THREAD

**Issue by fhferreira** [pvtl/voyager-frontend#62]
- Installation request for pvtl/voyager-frontend ^0.9.2 -> satisfiable by pvtl/voyager-frontend[0.9.2].
    - Conclusion: remove laravel/framework v6.0.0

**Comment by twelvee** [comment]
laravel 6.x same issuse

**Comment by web-developer-pk** [comment]
Cannot install Voyager Frontend on Laravel 6.0.3.
Voyager Admin is working fine on same installation...

**Comment by ronysur007** [comment]
- Installation request for pvtl/voyager-frontend ^0.9.3 -> satisfiable by pvtl/voyager-frontend[0.9.3].
    - Conclusion: remove laravel/framework v6.2.0
    - Conclusion: don't install laravel/framework v6.2.0

**Comment by hgoncalves** [comment]
Same issue for me

**Comment by schrink** [comment]
Any updates on this?

**Comment by thegugaru** [comment]
> * Installation request for pvtl/voyager-frontend ^0.9.3 -> satisfiable by pvtl/voyager-frontend[0.9.3].
>   
>   * Conclusion: remove laravel/framework v6.2.0
>   * Conclusion: don't install laravel/framework v6.2.0

This is not a solution

**Comment by Liam-PVTL** [comment]
Installation should work on Laravel 6.0+ now (as of Nov 2019) - Composer should pick up version 0.9.4+.
