### ISSUE TITLE
Installation Fails

### ISSUE THREAD

**Issue by thegugaru** [pvtl/voyager-frontend#64]
I have been using Laravel for years and I have never seen this error before. I am assuming it has to do with Voyager Frontend and yes Voyager works fine. Please advise!

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

Installation failed, reverting ./composer.json to its original content.

>   [ErrorException]
>   "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

**Comment by thegugaru** [comment]
To be clear I am running Laravel 5.5.48

**Comment by Liam-PVTL** [comment]
This package is now only supported by Laravel 6.0+. Try updating Laravel - I will close this issue for now.
