### ISSUE TITLE
Users in admin get_class error

### ISSUE THREAD

**Issue by pdw-studio** [pvtl/voyager-frontend#65]
### **Version information**
Laravel 6.2
Voyager 1.3
Voyager 0.9.4
PHP 7.2.19
MySQL 5.7.24

### **Details**
Just instaled Voyager and everythings works fine untill i install Voyager Frontend.
Than when visiting Users page in admin i get this error: get_class() expects parameter 1 to be object, string given (View: C:\laragon\www\laratest\vendor\tcg\voyager\resources\views\bread\partials\actions.blade.php) at line 4

**Comment by rubykoul** [comment]
@pdw-studio 
Use this:
https://github.com/pvtl/voyager-frontend/pull/63/commits/183680bbc0a21f4462e1c5d2f7179eafd9d779f9

**Comment by pdw-studio** [comment]
Thank you a lot, 
it works!
