### ISSUE TITLE
Deprecation warning: require.voyager-themes is invalid

### ISSUE THREAD

**Issue by RiseUpDroid** [pvtl/voyager-frontend#66]
Deprecation warning: require.voyager-themes is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.

**Comment by Liam-PVTL** [comment]
This is not an error with this package. In your composer.json it sounds like you have "voyager-themes" instead of "devdojo/voyager-themes". See here: https://github.com/thedevdojo/voyager-themes/issues/23

**Comment by chynawhyte** [comment]
After receiving the same error and finding the fix here, I've updated the composer.json file with the "devdojo/voyager-themes" and I get the message: "The requested package devdojo/voyager-themes could not be found in any version" when doing compose update
