### ISSUE TITLE
Laravel 7 support

### ISSUE THREAD

**Issue by mwkcoding** [pvtl/voyager-frontend#70]
Please add Laravel 7 support

**Comment by mrpastewart** [comment]
+1 yeah i tried to install to a fresh laravel 7 install and it fails to install and composer reverts with the following:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pvtl/voyager-frontend 0.9.6 requires spatie/laravel-sitemap ~5.5.0 -> satisfiable by spatie/laravel-sitemap[5.5.0].
    - Installation request for pvtl/voyager-frontend ^0.9.6 -> satisfiable by pvtl/voyager-frontend[0.9.6].
    - Conclusion: remove laravel/framework v7.1.3
    - Conclusion: don't install laravel/framework v7.1.3
    - spatie/laravel-sitemap 5.5.0 requires illuminate/support ~5.8.0|^6.0 -> satisfiable by illuminate/support[5.8.x-dev, 6.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - don't install illuminate/support 5.8.x-dev|don't install laravel/framework v7.1.3
    - don't install illuminate/support 6.x-dev|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.0|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.11|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.12|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.14|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.15|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.17|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.18|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.19|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.2|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.20|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.22|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.24|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.27|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.28|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.29|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.3|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.30|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.31|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.32|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.33|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.34|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.35|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.36|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.4|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.8|don't install laravel/framework v7.1.3
    - don't install illuminate/support v5.8.9|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.0.0|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.0.1|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.0.2|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.0.3|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.0.4|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.1.0|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.10.0|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.11.0|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.12.0|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.13.0|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.13.1|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.14.0|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.15.0|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.15.1|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.16.0|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.17.0|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.17.1|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.18.0|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.18.1|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.2.0|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.3.0|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.4.1|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.5.0|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.5.1|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.5.2|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.6.0|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.6.1|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.6.2|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.7.0|don't install laravel/framework v7.1.3
    - don't install illuminate/support v6.8.0|don't install laravel/framework v7.1.3
    - Installation request for laravel/framework (locked at v7.1.3, required as ^7.0) -> satisfiable by laravel/framework[v7.1.3].

**Comment by Mabudigital** [comment]
Same here!

**Comment by Sumit199612** [comment]
Exactly I have also facing with this same issue

**Comment by lukewmoore** [comment]
Hi @mwkcoding, Laravel 7 support has been added as of voyager-frontend version 0.9.8.
