### ISSUE TITLE
Full Size image is never used

### ISSUE THREAD

**Issue by rain2o** [pvtl/voyager-frontend#71]
In the ImageResize helper `imageUrl` function, the condition for returning the original image is never met because the condition is invalid.

see [ImageResize::33](https://github.com/pvtl/voyager-frontend/blob/8ebd470c8ccf5714ba8a6c8fd2a3d3bfdbd47d8f/src/Helpers/ImageResize.php#L33)

```if ((int)$width === null && (int)$height === null)```

It looks like it's partially trying to check two different ways. It either needs to compare `null` without the type-casting, or compare to `0` with the type casting.

Either `if ($width === null && $height === null) {` or `if ((int)$width === 0 && (int)$height === 0) {` should work.

**Comment by Liam-PVTL** [comment]
Thanks @rain2o you're absolutely right.
