### ISSUE TITLE
LogicException: Unable to prepare route [account] for serialization. Another route has already been assigned name [voyager-frontend.account]

### ISSUE THREAD

**Issue by prashantspawar** [pvtl/voyager-frontend#74]
Hi,

Getting Error:
LogicException
  Unable to prepare route [account] for serialization. Another route has already been assigned name [voyager-frontend.account].

![voyager-frontend-error](https://user-images.githubusercontent.com/25509834/82111785-0fc0b500-9765-11ea-896b-492ad4ed9551.png)

**Comment by Liam-PVTL** [comment]
@prashantspawar  do you have any steps to replicate this in a fresh project? 

What version of Voyager, Laravel & php are you using? 

Do you have this route defined in your routes file(s)?
