### ISSUE TITLE
Compatibility with Voyager v1.4.2

### ISSUE THREAD

**Issue by Ezyweb-uk** [pvtl/voyager-frontend#75]
Is Voyager-Frontend likely to be compatible with Voyager v1.4.2? Anyone tested?

**Comment by vitormicillo** [comment]
yes 100% compatible why?

**Comment by Ezyweb-uk** [comment]
Great! Only because I'm about to install on an existing Voyager 1.4 install and composer.json for voyager-frontend lists voyager 1.3.

**Comment by vitormicillo** [comment]
go ahead, I have the latest version of all packages here and it works well

**Comment by Ezyweb-uk** [comment]
Yes I can confirm the same. Nice work, and clear instructions. Thanks!
