### ISSUE TITLE
voyager-frontend does not work with configuration caching

### ISSUE THREAD

**Issue by jaromic** [pvtl/voyager-frontend#79]
# Summary 

When using cached configuration (which is recommended on a production site), laravel does not load the `.env` file, but only the cached configuration file `config/cache.php`.

https://laravel.com/docs/7.x/configuration

Calls like `env('APP_URL')` do not work in such an environment, and we should use `config('app.url')`, `config('app.asset_url')` etc. instead.

# Steps

* use voyager-frontend's `imageUrl()` in an environment with cached configuration

# Expected

* correct URL output

# Actual

* all URLs start with http://localhost

# Environment

Laravel 7
voyager 1.1.8
voyager-frontend 0.9.8

**Comment by jaromic** [comment]
It looks like this has been fixed in 1.0.1, we will be re-testing with that.

**Comment by Liam-PVTL** [comment]
Thanks @jaromic, this is a confirmed issue. 

Feel free to create a PR to switch it to a config() call. This is certainly on the list to update now.

**Comment by Liam-PVTL** [comment]
This has been amended in 1.0.2!
