### ISSUE TITLE
Class VoyagerFrontendDatabaseSeeder does not exist 

### ISSUE THREAD

**Issue by hamza-mostafa** [pvtl/voyager-frontend#8]
Hello,
Apologies for making this long, however I wanted to give you clear and full information.
my versions:
laravel:5.5
voyager:1.0.17
voyager-frontend:0.5.0.
After a fresh installation of laravel, voyager, voyager-frontend, 
`composer du && php artisan voyager-frontend:install` produces the below:
```
Deleting Laravel's default assets, to make way for ours
Remove default welcome page
Remove default web route
Copying authentication views to main project
Copying our webpack.mix.js to the project root
Publishing the Voyager assets, database, and config files
Publishing complete.
Updating Root package.json to include dependencies
Dumping the autoloaded files and reloading all new files
Migrating the database tables into your application
Migrating: 2018_01_07_224316_add_fields_to_post_table
Migrated:  2018_01_07_224316_add_fields_to_post_table
Seeding data into the database
```
with the error:
```
In Container.php line 752:
Class VoyagerFrontendDatabaseSeeder does not exist 
```
this is my compopser.lock
https://github.com/pvtl/voyager-frontend/files/1949704/composer.zip

and this is my app/database/seeds folder

![](https://user-images.githubusercontent.com/30126495/39286328-8c43eae0-491d-11e8-9d88-cc6d3cd4ed3a.png)

After checking with @Jean-PierreGassin, I tested that on another 2 machines to make sure that it is not permissions issue, and one of the machines are managed by serverpilot, also the voyager seeders went through.
I repeated the process 2 or 3 times with each time du and clearing the cache, config, and clear-compiled.
Also, the assets folder wasn't copied as well.

**Comment by mcnamee** [comment]
Hey @hamza-mostafa 
Firstly - thanks for testing, submitting issues and bearing with us while we build this out. We realise these issues are a bit of a pain, but you've been really helpful.

Would you be able to try with the latest version of Voyager Frontend (currently v0.7)? I've just run a successful install with:

1. laravel/framework - 5.5
1. tcg/voyager - 1.0.17
1. pvtl/voyager-pages - 0.1
1. pvtl/voyager-frontend - 0.7

**Comment by mcnamee** [comment]
If you're in a fresh project, I'd suggest re-installing (from scratch). However generally you can change package versions by updating your existing project's `composer.json` and running `composer install`
