### ISSUE TITLE
Overriding Views not working 

### ISSUE THREAD

**Issue by ohm-meter** [pvtl/voyager-frontend#83]
How can i force the override ? Because i have create Folders and Files like described:
![Projekt_–_breadcrumbs_blade_php](https://user-images.githubusercontent.com/49782166/116569377-9e442d00-a909-11eb-9a29-d07b6ab3c2e3.png)

But if i change something nothing worked

**Comment by vitormicillo** [comment]
the folder you try to override is wrong, the correct name is vendor, not
vendors.

**Comment by ohm-meter** [comment]
Yes you are right!!
